steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/poetic-result-290509/trainedteachers', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/poetic-result-290509/trainedteachers']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'trainedteachers', '--image', 'gcr.io/poetic-result-290509/trainedteachers', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
-images:
  - gcr.io/poetic-result-290509/trainedteachers